#ifndef HEADER_DISTR__PLUGIN_INFO
#define HEADER_DISTR__PLUGIN_INFO

#define DISTRHO_PLUGIN_NAME        "MultiScaleBody"
#define DISTRHO_PLUGIN_URI         "urn:distrho:multiscalebody"
#define DISTRHO_PLUGIN_CLAP_ID     "studio.kx.distrho.multiscalebody"

#define DISTRHO_PLUGIN_NUM_INPUTS  1
#define DISTRHO_PLUGIN_NUM_OUTPUTS 2

#define DISTRHO_PLUGIN_HAS_UI      1
#define DISTRHO_PLUGIN_IS_RT_SAFE  1
#define DISTRHO_PLUGIN_IS_SYNTH    1
#define DISTRHO_PLUGIN_WANT_MIDI_INPUT 1
#define DISTRHO_PLUGIN_WANT_STATE 1
#define DISTRHO_PLUGIN_WANT_FULL_STATE 1
#define DISTRHO_PLUGIN_WANT_TIMEPOS 1
#define DISTRHO_UI_CUSTOM_WIDGET_TYPE DGL_NAMESPACE::LVGLTopLevelWidget
#define DISTRHO_UI_DEFAULT_WIDTH  1440
#define DISTRHO_UI_DEFAULT_HEIGHT 860
#define DISTRHO_UI_USER_RESIZABLE 1
#define DISTRHO_UI_URI DISTRHO_PLUGIN_URI "#UI"

#endif
